# Generated by Django 3.2 on 2021-04-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100)),
                ('weapon_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponAttackStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=50)),
                ('weapon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponAttackDamageDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.FloatField()),
                ('puncture', models.FloatField()),
                ('slash', models.FloatField()),
                ('weapon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat.weaponattackstats')),
            ],
        ),
    ]
