# Generated by Django 3.2 on 2021-05-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0002_auto_20210511_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponattackstats',
            old_name='reload_speed',
            new_name='reload_time',
        ),
    ]
