# Generated by Django 3.2.2 on 2021-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0003_rename_reload_speed_weaponattackstats_reload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponattackstats',
            name='multishot',
            field=models.FloatField(default=1.0),
        ),
    ]
