# Generated by Django 3.2.2 on 2021-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0004_alter_weaponattackstats_multishot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('mod_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('target_weapon_name', models.CharField(max_length=100)),
                ('target_weapon_slot', models.CharField(max_length=100)),
                ('target_weapon_type', models.CharField(max_length=100)),
                ('crit_chance', models.FloatField(default=0.0)),
                ('crit_multiplier', models.FloatField(default=0.0)),
                ('status_chance', models.FloatField(default=0.0)),
                ('multishot', models.FloatField(default=1.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('fire_rate', models.FloatField(default=0.0)),
                ('charge_speed', models.FloatField(default=0.0)),
                ('magazine_size', models.FloatField(default=0.0)),
                ('max_ammo', models.FloatField(default=0.0)),
                ('reload_time', models.FloatField(default=0.0)),
                ('damage_falloff_percent', models.FloatField(default=0.0)),
                ('punch_through', models.FloatField(default=0.0)),
                ('impact', models.FloatField(default=0.0)),
                ('puncture', models.FloatField(default=0.0)),
                ('slash', models.FloatField(default=0.0)),
                ('heat', models.FloatField(default=0.0)),
                ('cold', models.FloatField(default=0.0)),
                ('electric', models.FloatField(default=0.0)),
                ('toxin', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='weapon_class',
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_slot',
            field=models.CharField(default='Primary', max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(default='Rifle', max_length=100),
        ),
        migrations.AlterField(
            model_name='weaponattackstats',
            name='attack_type',
            field=models.CharField(default='Primary', max_length=100),
        ),
    ]
