# Generated by Django 3.2.2 on 2021-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0005_auto_20210522_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='damage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mod',
            name='multishot',
            field=models.FloatField(default=0.0),
        ),
    ]
