# Generated by Django 3.2.2 on 2021-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0006_auto_20210522_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistancesOfDefenceResource',
            fields=[
                ('defence_resource_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('impact', models.FloatField(default=0.0)),
                ('puncture', models.FloatField(default=0.0)),
                ('slash', models.FloatField(default=0.0)),
                ('heat', models.FloatField(default=0.0)),
                ('cold', models.FloatField(default=0.0)),
                ('electric', models.FloatField(default=0.0)),
                ('toxin', models.FloatField(default=0.0)),
                ('blast', models.FloatField(default=0.0)),
                ('corrosive', models.FloatField(default=0.0)),
                ('gas', models.FloatField(default=0.0)),
                ('magnetic', models.FloatField(default=0.0)),
                ('radiation', models.FloatField(default=0.0)),
                ('viral', models.FloatField(default=0.0)),
            ],
        ),
    ]
