# Generated by Django 3.2.2 on 2021-05-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0008_fraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('target_shield_base_value', models.FloatField(default=0)),
                ('target_health_base_value', models.FloatField(default=0)),
                ('target_armor_base_value', models.FloatField(default=0)),
                ('target_armor_type', models.ManyToManyField(related_name='target_armor_type', to='bat.ResistancesOfDefenceResource')),
                ('target_fraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bat.fraction')),
                ('target_health_type', models.ManyToManyField(related_name='target_health_type', to='bat.ResistancesOfDefenceResource')),
                ('target_shield_type', models.ManyToManyField(related_name='target_shield_type', to='bat.ResistancesOfDefenceResource')),
            ],
        ),
    ]
