# Generated by Django 3.2.2 on 2021-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0009_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='mod_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mod',
            name='mod_tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
