# Generated by Django 3.2.2 on 2021-06-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0011_rename_crit_multiplier_mod_crit_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='target_armor_base_value',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_armor_type',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_health_base_value',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_health_type',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_shield_base_value',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_shield_type',
        ),
    ]
