# Generated by Django 3.2.2 on 2021-06-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0012_auto_20210604_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_armor_base_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='target_armor_type',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='armor_type', to='bat.resistancesofdefenceresource'),
        ),
        migrations.AddField(
            model_name='target',
            name='target_health_base_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='target_health_type',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='health_type', to='bat.resistancesofdefenceresource'),
        ),
        migrations.AddField(
            model_name='target',
            name='target_shield_base_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='target_shield_type',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='shield_type', to='bat.resistancesofdefenceresource'),
        ),
    ]
